import { environment } from '../environment/environment';

export const API_CONFIG = {
  BASE_URL: environment.apiUrl,
  BLACKLIST_ENDPOINT: `${environment.apiUrl}/fontana/api/v1/auth/blacklist`,
  PANIC_BUTTON: `${environment.apiUrl}/fontana/api/v1/dmx/panic`,
  REFRESH_TOKEN_AUTH: `${environment.apiUrl}/fontana/api/v1/auth/refreshtoken`,
  AUTH_AUTHENTICATE: `${environment.apiUrl}/fontana/api/v1/auth/authenticate`,
  LOGS: `${environment.apiUrl}/fontana/api/v1/log`,
  LIVE_CONTROL_SESSION: `${environment.apiUrl}/fontana/api/v1/session`,
  CURRENT_STATE: `${environment.apiUrl}/fontana/api/v1/dmx/state`,
  CLOSE_SESSION: `${environment.apiUrl}/fontana/api/v1/session/close`,
  GET_MY_TEMPLATES: `${environment.apiUrl}/fontana/api/v1/template/myTemplatesCards`,
  GET_MY_TEMPLATES_SNIPPETS: `${environment.apiUrl}/fontana/api/v1/template/myTemplatesSnippet`,
  GET_DRAFT_TEMPLATES_SNIPPETS: `${environment.apiUrl}/fontana/api/v1/template/draftTemplatesSnippet`,
  GET_PUBLIC_TEMPLATES: `${environment.apiUrl}/fontana/api/v1/template/publicTemplatesCards`,
  GET_PUMP_POWER_MULTIPLIER: `${environment.apiUrl}/fontana/api/v1/dmx/getPumpPowerMultiplier`,
  GET_API_VALIDATION_STATUS: `${environment.apiUrl}/fontana/api/v1/dmx/getApiValidationStatus`,
  POST_PUMP_POWER_MULTIPLIER: `${environment.apiUrl}/fontana/api/v1/dmx/changePumpPowerMultiplier`,
  POST_API_VALIDATION_STATUS: `${environment.apiUrl}/fontana/api/v1/dmx/enableApiValidation`,
  GET_SPECIAL_DAYS: `${environment.apiUrl}/fontana/api/v1/schedule/get/month`,
  GET_SCHEDULES_FOR_DATE: `${environment.apiUrl}/fontana/api/v1/schedule/get/day`,
  PUT_UPDATE_SCHEDULE: `${environment.apiUrl}/fontana/api/v1/schedule/update`,
  POST_ADD_SCHEDULE: `${environment.apiUrl}/fontana/api/v1/schedule/add`,
  DELETE_SCHEDULE: `${environment.apiUrl}/fontana/api/v1/schedule/delete`,
  STOP_SCHEDULE: `${environment.apiUrl}/fontana/api/v1/schedule/stop`,
  SESSION_NOTIFICATION_AMOUNT: `${environment.apiUrl}/fontana/api/v1/session/non-displayed-amount/`,
  SESSION_FIND_ALL_WITH_OPTIONAL_PARAM: `${environment.apiUrl}/fontana/api/v1/session`,
  SESSION_UPDATE_SINGLE_SESSION_WATCHER: `${environment.apiUrl}/fontana/api/v1/session`,
  SESSION_UPDATE_ALL_SESSIONS_WATCHER: `${environment.apiUrl}/fontana/api/v1/session/all/watcher`,
  POST_TEMPLATE: `${environment.apiUrl}/fontana/api/v1/template`,
  GET_SNIPPETS: `${environment.apiUrl}/fontana/api/v1/schedule/get/snippets`,
  USER_ENDPOINT: `${environment.apiUrl}/fontana/api/v1/user`,
  UPDATE_JET: `${environment.apiUrl}/fontana/api/v1/dmx/update/jet`,
  UPDATE_PUMP: `${environment.apiUrl}/fontana/api/v1/dmx/update/pump`,
  UPDATE_LIGHT: `${environment.apiUrl}/fontana/api/v1/dmx/update/light`,
  UPDATE_LED: `${environment.apiUrl}/fontana/api/v1/dmx/update/led`,
  HIDE_TEMPLATE: `${environment.apiUrl}/fontana/api/v1/template/delete`
};
